dist: bionic
language: python
python:
  - "3.7"
addons:
  apt:
    packages:
    - jq
branches:
  only:
  - master
install:
  - pip install yq
  - pip install WeasyPrint
before_script:
  - nvm install 10
  - nvm use 10
  - npm install gulp-cli -g
  - cd preview
  - npm ci                      # Install from package-lock.json
  # The gulp command below relies on variable $REPOSITORY_URL
  - export REPOSITORY_URL=${TRAVIS_REPO_SLUG}.git
  - gulp playbook
  # Run Antora
  - export ANTORA_COMPONENT_NAME="$(yq -r .name ${TRAVIS_BUILD_DIR}/antora.yml)"
  - export COMPONENT_VERSION="$(yq -r .version ${TRAVIS_BUILD_DIR}/antora.yml)"
  - export COMPONENT_NAME=$(yq -r '.name|.[3:]|sub("-";"_";"g")' ${TRAVIS_BUILD_DIR}/antora.yml)
  - export COMPONENT_LANGUAGE=$(yq -r '.name|.[0:2]' ${TRAVIS_BUILD_DIR}/antora.yml)
  - export LAST_COMMIT_DATE_ISO=$(git log -1 --format="%cI")
  - export HTML_FILE="${TRAVIS_BUILD_DIR}/preview/build/$ANTORA_COMPONENT_NAME/$COMPONENT_VERSION/PDF/index.html"
  - export DEPLOY_DIR="${TRAVIS_BUILD_DIR}/preview/build/PDF"
  - export PDF_BASENAME="barcelona_${COMPONENT_NAME}_v${COMPONENT_VERSION}_${LAST_COMMIT_DATE_ISO}.${COMPONENT_LANGUAGE}.pdf"
  - export PDF_FILE="${DEPLOY_DIR}/modules/ROOT/assets/attachments/${PDF_BASENAME}"
  - node_modules/.bin/antora --stacktrace --fetch --html-url-extension-style=indexify --attribute "pdf-basename=${PDF_BASENAME}" site.patched.yml
script:
  # Generate PDF
  - mkdir -p $DEPLOY_DIR/modules/ROOT/assets/attachments
  - weasyprint -p $HTML_FILE $PDF_FILE
  - ls -l $DEPLOY_DIR/modules/ROOT/assets/attachments
deploy:                         # Push to pdf branch of the origin remote (GitHub)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN   # Set in the settings page of your repository, as a secure variable
  keep_history: true            # Incremental commit instead of push force
  local_dir: $TRAVIS_BUILD_DIR/preview/build/PDF
  target_branch: pdf
